# MathJax Support
title: X.Blockchain
description: Technical White Paper
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
author:
  name: "Yongseok Kwon"
  email: "yskown@certon.co.kr"
  url: "http://xblocksys.com"

mathjax:
  enable: true
  per_page: true
  cdn: //xblocksys.github.io/Documentation/WhitePaper?config=TeX-AMS-MML_HTMLorMML

theme: jekyll-theme-cayman
