# MathJax Support
title: X.Blockchain
description: "Technical White Paper"
avatar: "https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png"
author:
  name: "Yongseok Kwon"
  email: "yskown@certon.co.kr"
  url: "http://xblocksys.com"
markdown: kramdown
theme: jekyll-theme-hacker
