# MathJax Support
title: X.Blockchain
description: "Technical White Paper"
author:
  name: "Yongseok Kwon"
  email: "yskown@xblocksys.com"
  url: "http://xblocksys.com"
markdown: kramdown
theme: jekyll-theme-cayman
